#include <cstring>

#include "ff.h"
#include "diskio.h"
#include "hardware/flash.h"
#include "hardware/sync.h"

extern "C" {
    // defined in ${CMAKE_BINARY_DIR}/fs_generated/disk.c (generated by CMake from ${CMAKE_CURRENT_LIST_DIR}/src/disk.img)
    // const keeps the array in flash (.rodata), avoiding copying it into RAM
    extern const unsigned char disk_img[];
    extern unsigned int disk_img_len;
}

#define DISK_SIZE disk_img_len
#define BLOCK_SIZE 0x80UL
#define SECTOR_COUNT (DISK_SIZE / BLOCK_SIZE)
#define SECTOR_SIZE 512U

DRESULT disk_ioctl(BYTE pdrv, BYTE cmd, void* buff) {
    switch (cmd) {
    case GET_BLOCK_SIZE:
        *(DWORD *)buff = (DWORD)BLOCK_SIZE;
        return DRESULT::RES_OK;
    case GET_SECTOR_COUNT:
        *(LBA_t *)buff = (LBA_t)SECTOR_COUNT;
        return DRESULT::RES_OK;
    case CTRL_SYNC:
        return DRESULT::RES_OK;
    default:
        return DRESULT::RES_ERROR;
    }
}

DSTATUS disk_initialize(BYTE pdrv) {
    return 0;
}

DSTATUS disk_status(BYTE pdrv) {
    return 0;
}

DRESULT disk_read(BYTE pdrv, BYTE* buff, LBA_t sector, UINT count) {
    // disk_img is memory-mapped in flash (XIP); plain memcpy suffices
    std::memcpy(buff, disk_img + sector * SECTOR_SIZE, count * SECTOR_SIZE);
    return DRESULT::RES_OK;
}

DRESULT disk_write(BYTE pdrv, const BYTE* buff, LBA_t sector, UINT count) {
    // Absolute offset from the start of flash to the first byte being written
    const uint32_t disk_flash_offset = reinterpret_cast<uint32_t>(disk_img) - XIP_BASE;
    const uint32_t write_offset = sector * SECTOR_SIZE;
    const uint32_t write_size   = count  * SECTOR_SIZE;

    // Flash erase granularity is FLASH_SECTOR_SIZE (4096 bytes).
    // Determine which flash sectors are touched by this write.
    const uint32_t first_flash_sector = (disk_flash_offset + write_offset) / FLASH_SECTOR_SIZE;
    const uint32_t last_flash_sector  = (disk_flash_offset + write_offset + write_size - 1) / FLASH_SECTOR_SIZE;

    uint8_t sector_buf[FLASH_SECTOR_SIZE];

    for (uint32_t fs_idx = first_flash_sector; fs_idx <= last_flash_sector; fs_idx++) {
        const uint32_t flash_sector_start = fs_idx * FLASH_SECTOR_SIZE;
        const uint32_t flash_sector_end   = flash_sector_start + FLASH_SECTOR_SIZE;

        // Read the full 4 KB flash sector into RAM so unrelated bytes are preserved
        std::memcpy(sector_buf,
                    reinterpret_cast<const uint8_t *>(XIP_BASE + flash_sector_start),
                    FLASH_SECTOR_SIZE);

        // Compute the byte range that overlaps between this flash sector and the write
        const uint32_t abs_write_start = disk_flash_offset + write_offset;
        const uint32_t abs_write_end   = abs_write_start + write_size;

        const uint32_t overlap_start = abs_write_start > flash_sector_start ? abs_write_start : flash_sector_start;
        const uint32_t overlap_end   = abs_write_end   < flash_sector_end   ? abs_write_end   : flash_sector_end;

        // Patch the sector buffer with the incoming data
        std::memcpy(sector_buf + (overlap_start - flash_sector_start),
                    buff        + (overlap_start - abs_write_start),
                    overlap_end - overlap_start);

        // Erase and reprogram with interrupts disabled to prevent any flash
        // access from interrupt handlers while XIP is temporarily suspended
        uint32_t saved_ints = save_and_disable_interrupts();
        flash_range_erase(flash_sector_start, FLASH_SECTOR_SIZE);
        flash_range_program(flash_sector_start, sector_buf, FLASH_SECTOR_SIZE);
        restore_interrupts(saved_ints);
    }

    return DRESULT::RES_OK;
}

DWORD get_fattime(void) {
    return 0;
}